<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            ['nome' => 'ABREULÂNDIA', 'codigo_ibge' => '1700251'],
            ['nome' => 'AGUIARNÓPOLIS', 'codigo_ibge' => '1700301'],
            ['nome' => 'ALIANÇA DO TOCANTINS', 'codigo_ibge' => '1700350'],
            ['nome' => 'ALMAS', 'codigo_ibge' => '1700400'],
            ['nome' => 'ALVORADA', 'codigo_ibge' => '1700707'],
            ['nome' => 'ANANÁS', 'codigo_ibge' => '1701002'],
            ['nome' => 'ANGICO', 'codigo_ibge' => '1701051'],
            ['nome' => 'APARECIDA DO RIO NEGRO', 'codigo_ibge' => '1701101'],
            ['nome' => 'ARAGOMINAS', 'codigo_ibge' => '1701309'],
            ['nome' => 'ARAGUACEMA', 'codigo_ibge' => '1701903'],
            ['nome' => 'ARAGUAÇU', 'codigo_ibge' => '1702000'],
            ['nome' => 'ARAGUAÍNA', 'codigo_ibge' => '1702109'],
            ['nome' => 'ARAGUANÃ', 'codigo_ibge' => '1702158'],
            ['nome' => 'ARAGUATINS', 'codigo_ibge' => '1702208'],
            ['nome' => 'ARAPOEMA', 'codigo_ibge' => '1702307'],
            ['nome' => 'ARRAIAS', 'codigo_ibge' => '1702406'],
            ['nome' => 'AUGUSTINÓPOLIS', 'codigo_ibge' => '1702554'],
            ['nome' => 'AURORA DO TOCANTINS', 'codigo_ibge' => '1702703'],
            ['nome' => 'AXIXÁ DO TOCANTINS', 'codigo_ibge' => '1702901'],
            ['nome' => 'BABAÇULÂNDIA', 'codigo_ibge' => '1703008'],
            ['nome' => 'BANDEIRANTES DO TOCANTINS', 'codigo_ibge' => '1703057'],
            ['nome' => 'BARRA DO OURO', 'codigo_ibge' => '1703073'],
            ['nome' => 'BARROLÂNDIA', 'codigo_ibge' => '1703107'],
            ['nome' => 'BERNARDO SAYÃO', 'codigo_ibge' => '1703206'],
            ['nome' => 'BOM JESUS DO TOCANTINS', 'codigo_ibge' => '1703305'],
            ['nome' => 'BRASILÂNDIA DO TOCANTINS', 'codigo_ibge' => '1703602'],
            ['nome' => 'BREJINHO DE NAZARÉ', 'codigo_ibge' => '1703701'],
            ['nome' => 'BURITI DO TOCANTINS', 'codigo_ibge' => '1703800'],
            ['nome' => 'CACHOEIRINHA', 'codigo_ibge' => '1703826'],
            ['nome' => 'CAMPOS LINDOS', 'codigo_ibge' => '1703842'],
            ['nome' => 'CARIRI DO TOCANTINS', 'codigo_ibge' => '1703867'],
            ['nome' => 'CARMOLÂNDIA', 'codigo_ibge' => '1703883'],
            ['nome' => 'CARRASCO BONITO', 'codigo_ibge' => '1703891'],
            ['nome' => 'CASEARA', 'codigo_ibge' => '1703909'],
            ['nome' => 'CENTENÁRIO', 'codigo_ibge' => '1704105'],
            ['nome' => 'CHAPADA DE AREIA', 'codigo_ibge' => '1704600'],
            ['nome' => 'CHAPADA DA NATIVIDADE', 'codigo_ibge' => '1705102'],
            ['nome' => 'COLINAS DO TOCANTINS', 'codigo_ibge' => '1705508'],
            ['nome' => 'COLMÉIA', 'codigo_ibge' => '1716703'],
            ['nome' => 'COMBINADO', 'codigo_ibge' => '1705557'],
            ['nome' => 'CONCEIÇÃO DO TOCANTINS', 'codigo_ibge' => '1705607'],
            ['nome' => 'COUTO MAGALHÃES', 'codigo_ibge' => '1706001'],
            ['nome' => 'CRISTALÂNDIA', 'codigo_ibge' => '1706100'],
            ['nome' => 'CRIXÁS DO TOCANTINS', 'codigo_ibge' => '1706258'],
            ['nome' => 'DARCINÓPOLIS', 'codigo_ibge' => '1706506'],
            ['nome' => 'DIANÓPOLIS', 'codigo_ibge' => '1707009'],
            ['nome' => 'DIVINÓPOLIS DO TOCANTINS', 'codigo_ibge' => '1707108'],
            ['nome' => 'DOIS IRMÃOS DO TOCANTINS', 'codigo_ibge' => '1707207'],
            ['nome' => 'DUERÉ', 'codigo_ibge' => '1707306'],
            ['nome' => 'ESPERANTINA', 'codigo_ibge' => '1707405'],
            ['nome' => 'FÁTIMA', 'codigo_ibge' => '1707553'],
            ['nome' => 'FIGUEIRÓPOLIS', 'codigo_ibge' => '1707652'],
            ['nome' => 'FILADÉLFIA', 'codigo_ibge' => '1707702'],
            ['nome' => 'FORMOSO DO ARAGUAIA', 'codigo_ibge' => '1708205'],
            ['nome' => 'FORTALEZA DO TABOCÃO', 'codigo_ibge' => '1708254'],
            ['nome' => 'GOIANORTE', 'codigo_ibge' => '1708304'],
            ['nome' => 'GOIATINS', 'codigo_ibge' => '1709005'],
            ['nome' => 'GUARAÍ', 'codigo_ibge' => '1709302'],
            ['nome' => 'GURUPI', 'codigo_ibge' => '1709500'],
            ['nome' => 'IPUEIRAS', 'codigo_ibge' => '1709807'],
            ['nome' => 'ITACAJÁ', 'codigo_ibge' => '1710508'],
            ['nome' => 'ITAGUATINS', 'codigo_ibge' => '1710706'],
            ['nome' => 'ITAPIRATINS', 'codigo_ibge' => '1710904'],
            ['nome' => 'ITAPORÃ DO TOCANTINS', 'codigo_ibge' => '1711100'],
            ['nome' => 'JAÚ DO TOCANTINS', 'codigo_ibge' => '1711506'],
            ['nome' => 'JUARINA', 'codigo_ibge' => '1711803'],
            ['nome' => 'LAGOA DA CONFUSÃO', 'codigo_ibge' => '1711902'],
            ['nome' => 'LAGOA DO TOCANTINS', 'codigo_ibge' => '1711951'],
            ['nome' => 'LAJEADO', 'codigo_ibge' => '1712009'],
            ['nome' => 'LAVANDEIRA', 'codigo_ibge' => '1712157'],
            ['nome' => 'LIZARDA', 'codigo_ibge' => '1712405'],
            ['nome' => 'LUZINÓPOLIS', 'codigo_ibge' => '1712454'],
            ['nome' => 'MARIANÓPOLIS DO TOCANTINS', 'codigo_ibge' => '1712504'],
            ['nome' => 'MATEIROS', 'codigo_ibge' => '1712702'],
            ['nome' => 'MAURILÂNDIA DO TOCANTINS', 'codigo_ibge' => '1712801'],
            ['nome' => 'MIRACEMA DO TOCANTINS', 'codigo_ibge' => '1713205'],
            ['nome' => 'MIRANORTE', 'codigo_ibge' => '1713304'],
            ['nome' => 'MONTE DO CARMO', 'codigo_ibge' => '1713601'],
            ['nome' => 'MONTE SANTO DO TOCANTINS', 'codigo_ibge' => '1713700'],
            ['nome' => 'PALMEIRAS DO TOCANTINS', 'codigo_ibge' => '1713809'],
            ['nome' => 'MURICILÂNDIA', 'codigo_ibge' => '1713957'],
            ['nome' => 'NATIVIDADE', 'codigo_ibge' => '1714203'],
            ['nome' => 'NAZARÉ', 'codigo_ibge' => '1714302'],
            ['nome' => 'NOVA OLINDA', 'codigo_ibge' => '1714880'],
            ['nome' => 'NOVA ROSALÂNDIA', 'codigo_ibge' => '1715002'],
            ['nome' => 'NOVO ACORDO', 'codigo_ibge' => '1715101'],
            ['nome' => 'NOVO ALEGRE', 'codigo_ibge' => '1715150'],
            ['nome' => 'NOVO JARDIM', 'codigo_ibge' => '1715259'],
            ['nome' => 'OLIVEIRA DE FÁTIMA', 'codigo_ibge' => '1715507'],
            ['nome' => 'PALMAS', 'codigo_ibge' => '1721000'],
            ['nome' => 'PALMEIRANTE', 'codigo_ibge' => '1715705'],
            ['nome' => 'PALMEIRÓPOLIS', 'codigo_ibge' => '1713809'],
            ['nome' => 'PARAÍSO DO TOCANTINS', 'codigo_ibge' => '1716109'],
            ['nome' => 'PARANÃ', 'codigo_ibge' => '1716208'],
            ['nome' => 'PAU D\'ARCO', 'codigo_ibge' => '1716307'],
            ['nome' => 'PEDRO AFONSO', 'codigo_ibge' => '1716505'],
            ['nome' => 'PEIXE', 'codigo_ibge' => '1716604'],
            ['nome' => 'PEQUIZEIRO', 'codigo_ibge' => '1716653'],
            ['nome' => 'PINDORAMA DO TOCANTINS', 'codigo_ibge' => '1717008'],
            ['nome' => 'PIRAQUÊ', 'codigo_ibge' => '1717206'],
            ['nome' => 'PIUM', 'codigo_ibge' => '1717503'],
            ['nome' => 'PONTE ALTA DO BOM JESUS', 'codigo_ibge' => '1717800'],
            ['nome' => 'PONTE ALTA DO TOCANTINS', 'codigo_ibge' => '1717909'],
            ['nome' => 'PORTO ALEGRE DO TOCANTINS', 'codigo_ibge' => '1718006'],
            ['nome' => 'PORTO NACIONAL', 'codigo_ibge' => '1718204'],
            ['nome' => 'PRAIA NORTE', 'codigo_ibge' => '1718303'],
            ['nome' => 'PRESIDENTE KENNEDY', 'codigo_ibge' => '1718402'],
            ['nome' => 'PUGMIL', 'codigo_ibge' => '1718451'],
            ['nome' => 'RECURSOLÂNDIA', 'codigo_ibge' => '1718501'],
            ['nome' => 'RIACHINHO', 'codigo_ibge' => '1718550'],
            ['nome' => 'RIO DA CONCEIÇÃO', 'codigo_ibge' => '1718659'],
            ['nome' => 'RIO DOS BOIS', 'codigo_ibge' => '1718709'],
            ['nome' => 'RIO SONO', 'codigo_ibge' => '1718758'],
            ['nome' => 'SAMPAIO', 'codigo_ibge' => '1718808'],
            ['nome' => 'SANDOLÂNDIA', 'codigo_ibge' => '1718840'],
            ['nome' => 'SANTA FÉ DO ARAGUAIA', 'codigo_ibge' => '1718865'],
            ['nome' => 'SANTA MARIA DO TOCANTINS', 'codigo_ibge' => '1718881'],
            ['nome' => 'SANTA RITA DO TOCANTINS', 'codigo_ibge' => '1718899'],
            ['nome' => 'SANTA ROSA DO TOCANTINS', 'codigo_ibge' => '1718907'],
            ['nome' => 'SANTA TEREZA DO TOCANTINS', 'codigo_ibge' => '1719004'],
            ['nome' => 'SANTA TEREZINHA DO TOCANTINS', 'codigo_ibge' => '1720002'],
            ['nome' => 'SÃO BENTO DO TOCANTINS', 'codigo_ibge' => '1720101'],
            ['nome' => 'SÃO FÉLIX DO TOCANTINS', 'codigo_ibge' => '1720150'],
            ['nome' => 'SÃO MIGUEL DO TOCANTINS', 'codigo_ibge' => '1720200'],
            ['nome' => 'SÃO SALVADOR DO TOCANTINS', 'codigo_ibge' => '1720259'],
            ['nome' => 'SÃO SEBASTIÃO DO TOCANTINS', 'codigo_ibge' => '1720309'],
            ['nome' => 'SÃO VALÉRIO', 'codigo_ibge' => '1720499'],
            ['nome' => 'SILVANÓPOLIS', 'codigo_ibge' => '1720655'],
            ['nome' => 'SÍTIO NOVO DO TOCANTINS', 'codigo_ibge' => '1720804'],
            ['nome' => 'SUCUPIRA', 'codigo_ibge' => '1720853'],
            ['nome' => 'TAGUATINGA', 'codigo_ibge' => '1720903'],
            ['nome' => 'TAIPAS DO TOCANTINS', 'codigo_ibge' => '1720937'],
            ['nome' => 'TALISMÃ', 'codigo_ibge' => '1720978'],
            ['nome' => 'TOCANTÍNIA', 'codigo_ibge' => '1721109'],
            ['nome' => 'TOCANTINÓPOLIS', 'codigo_ibge' => '1721208'],
            ['nome' => 'TUPIRAMA', 'codigo_ibge' => '1721257'],
            ['nome' => 'TUPIRATINS', 'codigo_ibge' => '1721307'],
            ['nome' => 'WANDERLÂNDIA', 'codigo_ibge' => '1722081'],
            ['nome' => 'XAMBIOÁ', 'codigo_ibge' => '1722107'],
        ];

        foreach ($municipios as $municipio) {
            Municipio::updateOrCreate(
                ['codigo_ibge' => $municipio['codigo_ibge']],
                [
                    'nome' => $municipio['nome'],
                    'uf' => 'TO',
                    'slug' => Str::slug($municipio['nome']),
                    'ativo' => true
                ]
            );
        }

        $this->command->info('Municípios do Tocantins cadastrados com sucesso!');
    }
}
